import { test, expect, type Page } from "@playwright/test";

/**
 * Phase 3 Milestone M2 — completion-gate E2E: chunk eviction + entity survival.
 *
 * THE defining acceptance test for Phase 3 world streaming:
 *
 *   WORLD ENTITY STATE  ≠  CHUNK CACHE STATE
 *
 * The party walks far enough from the demo hostile's chunk that the chunk is
 * automatically evicted (distance > PREFETCH_MARGIN + 1 from the viewport),
 * then returns. The hostile must retain its identity/state bit-identically,
 * and the chunk geometry must regenerate deterministically.
 *
 * Deterministic fixture facts (EXPLORE_WORLD_SEED = 20260817):
 *   • Party spawns at (8, 8) — chunk (0, 0).
 *   • Demo hostile "overworld_orc_1" at (20, 8) — chunk (1, 0), hp 15/15.
 *   • World region 64×64 (chunks 0..3 × 0..3); viewport 12×10.
 *   • WALK_PATH below is a verified pillar-free Chebyshev path from spawn to
 *     (58, 58) (far corner — chunk (3,3), Chebyshev distance 3 from chunk
 *     (1,0), beyond the eviction threshold of 2). Generated by BFS over the
 *     actual deterministic terrain; the "walk path is passable" unit test in
 *     evictionPolicy.test.ts anchors it against generation drift.
 *
 * Diagnostics: window.__worldDebug(cx, cy) (installed only with ?e2e) returns
 * a read-only snapshot: chunk residency, geometry hash, held chunks, and all
 * registry entities. The traversal itself is real UI interaction.
 */

const TILE = '[data-testid="board-tile"]';
const LOCATION = '[data-testid="exploration-location"]';
const HOSTILE_CHUNK = { cx: 1, cy: 0 };

// Verified floor path (BFS over the deterministic world; see header note).
const WALK_PATH: [number, number][] = [
  [9, 7], [10, 8], [11, 9], [12, 10], [13, 11], [14, 12], [15, 13], [16, 14],
  [17, 15], [18, 16], [19, 17], [20, 18], [21, 19], [22, 20], [23, 21],
  [24, 22], [25, 23], [26, 24], [27, 25], [28, 26], [29, 27], [30, 28],
  [30, 29], [31, 30], [32, 31], [33, 32], [34, 33], [35, 34], [36, 35],
  [37, 36], [38, 37], [39, 38], [40, 39], [41, 40], [42, 41], [42, 42],
  [43, 43], [44, 44], [45, 45], [46, 46], [47, 47], [48, 48], [49, 49],
  [50, 50], [51, 51], [52, 52], [53, 53], [54, 54], [55, 55], [56, 56],
  [57, 57], [58, 58],
];

interface WorldDebugSnapshot {
  residency: string;
  geometryHash: string | null;
  heldChunks: { cx: number; cy: number; residency: string }[];
  entities: { worldId: string; defId: string; wx: number; wy: number; hp: number; maxHp: number; alive: boolean }[];
}

async function worldDebug(page: Page, cx: number, cy: number): Promise<WorldDebugSnapshot> {
  const snap = await page.evaluate(
    ([x, y]) => (window as unknown as { __worldDebug?: (cx: number, cy: number) => unknown }).__worldDebug?.(x, y) ?? null,
    [cx, cy],
  );
  expect(snap, "world debug hook should be available in exploration").not.toBeNull();
  return snap as WorldDebugSnapshot;
}

async function stepTo(page: Page, wx: number, wy: number) {
  await expect
    .poll(
      async () => {
        await page.locator(`${TILE}[data-world-wx="${wx}"][data-world-wy="${wy}"]`).click();
        return page.locator(LOCATION).textContent();
      },
      { timeout: 10_000 },
    )
    .toContain(`(${wx}, ${wy})`);
}

async function walk(page: Page, path: [number, number][]) {
  for (const [wx, wy] of path) await stepTo(page, wx, wy);
}

function orcOf(snap: WorldDebugSnapshot) {
  return snap.entities.filter((e) => e.worldId === "overworld_orc_1");
}

test.describe("Phase 3 completion gate — leave, evict, return", () => {
  test("entity survives chunk eviction with identical identity and state; geometry regenerates deterministically", async ({ page }) => {
    test.setTimeout(180_000);
    await page.goto("/?e2e");
    await page.getByRole("button", { name: "Explore World" }).click();
    await expect(page.locator(LOCATION)).toContainText("(8, 8)");

    // ── 1-3. Establish + verify the entity's initial identity/state ─────────
    // Wait until the hostile's chunk is streamed in near spawn.
    await expect
      .poll(async () => (await worldDebug(page, HOSTILE_CHUNK.cx, HOSTILE_CHUNK.cy)).residency, { timeout: 15_000 })
      .toBe("RESIDENT");
    const initial = await worldDebug(page, HOSTILE_CHUNK.cx, HOSTILE_CHUNK.cy);
    const orcBefore = orcOf(initial);
    expect(orcBefore).toHaveLength(1);
    expect(orcBefore[0]).toEqual({
      worldId: "overworld_orc_1", defId: "orc", wx: 20, wy: 8,
      hp: 15, maxHp: 15, alive: true,
    });
    expect(initial.geometryHash).not.toBeNull();
    const geometryBefore = initial.geometryHash;
    const entitiesBefore = [...initial.entities].sort((a, b) => a.worldId.localeCompare(b.worldId));

    // ── 4-6. Traverse far away; streaming/eviction settles; chunk evicted ──
    await walk(page, WALK_PATH);
    await expect(page.locator(LOCATION)).toContainText("(58, 58)");
    await expect
      .poll(async () => (await worldDebug(page, HOSTILE_CHUNK.cx, HOSTILE_CHUNK.cy)).residency, { timeout: 15_000 })
      .toBe("UNLOADED");

    // Entity survives eviction: registry untouched (geometry-only eviction).
    const during = await worldDebug(page, HOSTILE_CHUNK.cx, HOSTILE_CHUNK.cy);
    expect(during.geometryHash).toBeNull(); // geometry really discarded
    expect(orcOf(during)).toHaveLength(1);
    expect(orcOf(during)[0]).toEqual(orcBefore[0]);

    // Resident set is bounded: with the viewport at chunk (3,3), every chunk
    // at Chebyshev distance > 2 must be evicted. Chunk (1,1) sits exactly at
    // the hysteresis threshold (distance 2) and is legitimately retained;
    // (0,0), (1,0), (0,1) are at distance 3 and must be gone.
    const beyondThreshold = during.heldChunks.filter(
      (c) => Math.max(3 - c.cx, 3 - c.cy, c.cx - 3, c.cy - 3) > 2,
    );
    expect(beyondThreshold).toHaveLength(0);

    // ── 7-8. Return; chunk becomes resident again ───────────────────────────
    await walk(page, [...WALK_PATH].reverse().slice(1).concat([[8, 8]]));
    await expect(page.locator(LOCATION)).toContainText("(8, 8)");
    await expect
      .poll(async () => (await worldDebug(page, HOSTILE_CHUNK.cx, HOSTILE_CHUNK.cy)).residency, { timeout: 15_000 })
      .toBe("RESIDENT");

    // ── 9-11. Same identity/state; deterministic geometry; no duplicates ───
    const after = await worldDebug(page, HOSTILE_CHUNK.cx, HOSTILE_CHUNK.cy);
    // Regenerated geometry is bit-identical.
    expect(after.geometryHash).toBe(geometryBefore);
    // Same entity identity, same world coordinates, same HP/alive state.
    const orcAfter = orcOf(after);
    expect(orcAfter).toHaveLength(1); // no duplicate entity was created
    expect(orcAfter[0]).toEqual(orcBefore[0]);
    // Authoritative world state unchanged by viewport movement: every entity
    // except the party (which we deliberately moved) is bit-identical.
    const entitiesAfter = [...after.entities].sort((a, b) => a.worldId.localeCompare(b.worldId));
    expect(entitiesAfter.filter((e) => e.worldId !== "party_avatar"))
      .toEqual(entitiesBefore.filter((e) => e.worldId !== "party_avatar"));
    // The party itself kept identity and hp — only position changed by walking.
    const partyAfter = entitiesAfter.find((e) => e.worldId === "party_avatar")!;
    const partyBefore = entitiesBefore.find((e) => e.worldId === "party_avatar")!;
    expect(partyAfter.hp).toBe(partyBefore.hp);
    expect(partyAfter.alive).toBe(true);
    expect({ wx: partyAfter.wx, wy: partyAfter.wy }).toEqual({ wx: 8, wy: 8 });
  });
});
